version: '3.8'  # docker-compose 파일 버전

services:
  learningFlow: # Spring Boot 서비스 이름
    build:
      context: .       # Dockerfile이 있는 디렉토리 (현재 디렉토리)
    image: app-image   # 생성될 Docker 이미지 이름
    ports:
      - "8080:8080" # 애플리케이션 포트 매핑
    #    image: mysql:8.0  # 사용할 Docker 이미지 (MySQL 8.0)
    container_name: learningFlow_db  # 컨테이너 이름
    restart: always  # 컨테이너 재시작 정책
    environment:
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      MAIL_USERNAME: ${MAIL_USERNAME}
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_ID: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_ID}
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_SECRET: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_SECRET}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      DB_URL: ${DB_URL}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}

volumes:
  db_data:

networks:
  default:
    driver: bridge