#배포용
## 유출 안되게 조심! gitignore에 **/application.yml 있나 체크 必 ##

spring:
  datasource: #RDS
    url: jdbc:mysql://lastcoffeedb.clwsq268wbl1.ap-northeast-2.rds.amazonaws.com/lastcoffeedb?createDatabaseIfNotExist=true&characterEncoding=UTF-8&characterSetResults=UTF-8
    username: admin
    password: lastcoffee!!!
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        ddl-auto: update
      generate-ddl: true
      show-sql: true
  #        dialect: org.hibernate.dialect.MySQL8Dialect
  #        show_sql: true
  #        format_sql: true
  #        use_sql_comments: true
  #        hbm2ddl:
  #          auto: update
  #        default_batch_fetch_size: 1000
  data:
    redis:
      host: localhost
      port: 6379
  jackson:
    default-property-inclusion: non_null
    serialization:
      fail-on-empty-beans: false

#cloud:
#  aws:
#    s3:
#      bucket: umc-7th-hackathon
#    region:
#      static: ap-northeast-2
#    stack:
#      auto: false
#    credentials:
#      accessKey: ${AWS_ACCESS_KEY_ID}
#      secretKey: ${AWS_SECRET_ACCESS_KEY}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true