#배포용
## 유출 안되게 조심! gitignore에 **/application.yml 있나 체크 必 ##

spring:
  datasource: #RDS
    url: jdbc:mysql://lastcoffeedb.clwsq268wbl1.ap-northeast-2.rds.amazonaws.com/lastcoffeedb?createDatabaseIfNotExist=true&characterEncoding=UTF-8&characterSetResults=UTF-8
    username: admin
    password: lastcoffee!!!
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    dialect: org.hibernate.dialect.MySQL8Dialect
  #        format_sql: true
  #        use_sql_comments: true
  #        hbm2ddl:
  #          auto: update
  #        default_batch_fetch_size: 1000
  jackson:
    default-property-inclusion: non_null
    serialization:
      fail-on-empty-beans: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: teamY.lastcoffee@gmail.com
    password: zmsy qwih sprj xlbp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  data:
    redis:
      host: redis
      port: 6379

#cloud:
#  aws:
#    s3:
#      bucket: umc-7th-hackathon
#    region:
#      static: ap-northeast-2
#    stack:
#      auto: false
#    credentials:
#      accessKey: ${AWS_ACCESS_KEY_ID}
#      secretKey: ${AWS_SECRET_ACCESS_KEY}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

# JWT 설정 추가
custom:
  jwt:
    secretKey: 8AJc6kC1DGeVjM4CHnWLlu8IYhAuaAOdmqonO7obud4\=
    access-token-validity-in-seconds: 259200000
    refresh-token-validity-in-seconds: 2419200000
